### PR TITLE
Jd 2022 09 repo cleanup

### PR DESCRIPTION
**Pull request by goapunk**

### CODE REVIEW

**Review by philli-m — COMMENTED** [review]
@goapunk looks good but not sure how to test it? or what it does?

**Review by fuzzylogic2000 — APPROVED** [review]
Haha, I didn't even know, we had this repo. But looks good to merge!

**Comment by khamui** [comment]
cool! not tested, just from reading code. looking fine.

out of curiosity: is this loading test performed locally or on a server? How long will it run (minutes, hours or even days)?

**Review by khamui — APPROVED** [review]
cool! not tested, just from reading code. looking fine.

out of curiosity: is this loading test performed locally or on a server? How long will it run (minutes, hours or even days)?

**Comment by goapunk** [comment]
@khamui good questions: we'll have to decide on that - it will run on multiple servers / locations, probably about an hour or so

**Pull request merged**
